// bend-schema's mutants: for each law, a change to core.bend that makes it
// false, and the def its proof must fail in. The harness is
// tools/bend_mutants.ts. test.sh runs this.

import { type Mutant, runMutants } from "../tools/bend_mutants.ts";

const EXACT = "check finds nothing exactly when the value conforms";

const MUTANTS: Mutant[] = [
  { law: "tagged_meaning", section: "a tagged case reads the object without its tag",
    from: "      pick_bool(is_tag(k, n, x), conforms(~rule, cs, drop_key(k, x), None{}), conforms(~rule, rest, x, None{}))",
    to: "      pick_bool(is_tag(k, n, x), conforms(~rule, cs, x, None{}), conforms(~rule, rest, x, None{}))",
    why: "a case sees the tag, so a strict case refuses a good value", failsIn: "LAWS.tagged_meaning" },
  { law: "tag_end_refuses", section: "the end of a tagged chain accepts nothing",
    from: "      False{}  # the end of a tagged chain: no case matched", to: "      True{}",
    why: "the end of a chain accepts anything", failsIn: "LAWS.tag_end_refuses" },
  { law: "drop_first", section: "drop_key takes out the first key it names",
    from: "      pick_raw(String.eq(j, k), o, RKey{j, v, drop_key(k, o)})", to: "      pick_raw(String.eq(j, k), RKey{j, v, o}, RKey{j, v, drop_key(k, o)})",
    why: "drop_key keeps the tag, so the case sees it", failsIn: "drop_self" },
  { law: "drop_other", section: "drop_key leaves every other key as it was",
    from: "      pick_raw(String.eq(j, k), o, RKey{j, v, drop_key(k, o)})", to: "      pick_raw(String.eq(j, k), o, drop_key(k, o))",
    why: "drop_key drops every key up to the tag (drop_self, which the section uses through the decoder tools, sees it first)", failsIn: "drop_self" },
  { law: "strict_meaning", section: "a strict object has no other key",
    from: "      Bool.and(in_names(k, ns), no_extra(ns, o))", to: "      in_names(k, ns)",
    why: "no_extra looks at the first key only, so a later unknown key conforms", failsIn: "strict_count" },
  { law: "check_exact", section: EXACT,
    from: "      pick_err(in_names(k, ns), extra_err(ns, o), Some{Err{AtKey{k} <> Nil{}, UnknownKey{}}})", to: "      pick_err(in_names(k, ns), None{}, Some{Err{AtKey{k} <> Nil{}, UnknownKey{}}})",
    why: "check stops after the first known key, so a later unknown key passes check though it does not conform", failsIn: "extra_exact" },
  { law: "check_accurate", section: "what check reports is there", with: [EXACT],
    from: "      guard(Bool.and(has_key(k, r), Bool.not(in_names(k, ns))), Some{UnknownKey{}})", to: "      guard(Bool.not(in_names(k, ns)), Some{NotObject{}})",
    why: "defect replays an unknown key as the wrong reason", failsIn: "extra_lift" },
  { law: "str_len_in_meaning", section: "a string's length is in its bounds",
    from: "  Bool.and(Nat.is_le(lo, String.length(x)), Nat.is_le(String.length(x), hi))",
    to: "  Bool.and(Nat.is_le(lo, String.length(x)), Nat.is_lt(String.length(x), hi))",
    why: "a string exactly hi long is refused (str_len_ok is the test str_len_in reports, and what an SStrLen means)", failsIn: "LAWS.str_len_in_meaning" },
  { law: "nat_in_meaning", section: "a number is in its bounds",
    from: "  Bool.and(Nat.is_le(lo, n), Nat.is_le(n, hi))",
    to: "  Nat.is_le(lo, n)",
    why: "a number past hi is let through (num_ok is the test nat_in reports, and what an SNatIn means)", failsIn: "LAWS.nat_in_meaning" },
  { law: "sbool_meaning", section: "a boolean, and nothing else",
    from: "      True{}  # any boolean is a boolean, and nothing else is",
    to: "      False{}  # any boolean is a boolean, and nothing else is",
    why: "a boolean is refused, so SBool accepts nothing", failsIn: "sbool_go" },
  { law: "snat_in_meaning", section: "a number's bounds, as a constructor",
    from: "      num_ok(lo, hi, n)",
    to: "      Nat.is_le(lo, n)",
    why: "SNatIn drops its upper bound, so a number past hi conforms (the first of the two lines that read num_ok: conforms', not bounds_ok's)", failsIn: "LAWS.snat_in_meaning" },
  { law: "sstr_len_meaning", section: "a string's length, as a constructor",
    from: "      Bool.and(conforms(~rule, s2, x, prev), len_ok(lo, hi, x))",
    to: "      Bool.and(conforms(~rule, s2, x, prev), True{})",
    why: "SStrLen drops its bounds, so a string of any length conforms", failsIn: "LAWS.sstr_len_meaning" },
  { law: "slist_len_meaning", section: "a list's element count, as a constructor",
    from: "      Bool.and(list_len_ok(lo, hi, r), conforms(~rule, s2, r, None{}))",
    to: "      conforms(~rule, s2, r, None{})",
    why: "SListLen drops its bounds, so a list of any element count conforms", failsIn: "LAWS.slist_len_meaning" },
  { law: "soptional_meaning", section: "an optional field, as a constructor",
    from: "      Bool.or(is_missing(x), conforms(~rule, inner, x, None{}))",
    to: "      Bool.or(is_missing(x), True{})",
    why: "SOptional accepts every value that is not absent, whatever the inner says", failsIn: "LAWS.soptional_meaning" },
  { law: "check_exact", section: EXACT,
    from: "      here(missing_or(x, NotNat{}))", to: "      None{}",
    why: "a value that is not a number passes check, though it does not conform", failsIn: "exact" },
  { law: "check_accurate", section: "what check reports is there", with: [EXACT],
    from: "      AtField{1n+k, n} <> q", to: "      AtField{k, n} <> q",
    why: "an error in a later field names the field before it", failsIn: "field_path_end" },
  { law: "check_exact", section: EXACT,
    from: "      first(check(~rule, s2, x, prev), rule(tag, x))", to: "      check(~rule, s2, x, prev)",
    why: "check forgets the rule, so a value the rule refuses passes", failsIn: "exact" },
  { law: "check_accurate", section: "what check reports is there", with: [EXACT],
    from: "      pick_why(conforms(~rule, s2, x, prev), rule_defect(rule(tag, x), q), defect(~rule, s2, x, prev, q))", to: "      defect(~rule, s2, x, prev, q)",
    why: "defect never replays the rule, so a rule's error is not found there", failsIn: "acc" },
  { law: "too_large_reported", section: "a too big value is reported where it stands",
    from: "      TooLarge{}", to: "      NotNat{}",
    why: "a node the codec refused to build is reported as the schema kind's own reason, so a value too big to walk reads as a value of the wrong shape", failsIn: "too_large_go" },
  { law: "enum_accepts", section: "every listed name is accepted",
    from: "      Bool.or(String.eq(x, n), in_names(x, t))", to: "      Bool.and(String.eq(x, n), in_names(x, t))",
    why: "a name is found only if it is every name, so listed names are refused", failsIn: "names_has" },
  { law: "enum_admits", section: "an accepted string is one of the names",
    from: "      Bool.or(String.eq(x, n), in_names(x, t))", to: "      Bool.or(True{}, in_names(x, t))",
    why: "any string is accepted by a non-empty list", failsIn: "one_of" },
  { law: "variant_meaning", section: "a variant chain, read by counting",
    from: "      pick_bool(is_missing(lookup(name, RKey{k, v, o})), conforms(~rule, rest, RKey{k, v, o}, None{}), Bool.and(conforms(~rule, vs, lookup(name, RKey{k, v, o}), None{}), none_present(rest, RKey{k, v, o})))",
    to: "      pick_bool(is_missing(lookup(name, RKey{k, v, o})), conforms(~rule, rest, RKey{k, v, o}, None{}), conforms(~rule, vs, lookup(name, RKey{k, v, o}), None{}))",
    why: "conforms stops at the first key it finds, so two keys conform", failsIn: "vm_raw" },
  { law: "check_exact", section: EXACT,
    from: "      here(TooLong{})", to: "      None{}",
    why: "check lets a tuple with an extra element through, though it does not conform", failsIn: "exact" },
  { law: "check_accurate", section: "what check reports is there", with: [EXACT],
    from: "      at_end(TooShort{}, q)", to: "      at_end(TooLong{}, q)",
    why: "defect replays a missing position as an extra one", failsIn: "acc" },
  { law: "tuple_meaning", section: "a tuple means its positions", with: ["a variant chain, read by counting"],
    from: "      Bool.and(conforms(~rule, ts, h, None{}), conforms(~rule, rest, t, None{}))", to: "      conforms(~rule, rest, t, None{})",
    why: "conforms skips a tuple's position (check would have to agree, and then exact and accurate still hold)", failsIn: "tm" },
  { law: "decode_encode", section: "what was written reads back as itself",
    from: "      Bool.and(wf(fs), Bool.and(fresh_f(n, rest), wf(rest)))", to: "      Bool.and(wf(fs), wf(rest))",
    why: "wf lets a record name a key twice, and the second field reads the first one's value", failsIn: "de" },
  { law: "decode_encode", section: "what was written reads back as itself",
    from: "      Bool.and(Bool.not(nullable(i)), wf(i))", to: "      wf(i)",
    why: "wf lets an optional value be optional, and Some{None} is written null, read back as None", failsIn: "de" },
  { law: "checked_decodes", section: "a value check accepts can be read",
    from: "      Some{x <> xs}", to: "      None{}",
    why: "dec refuses every non-empty list, though a list of conforming elements conforms", failsIn: "some_cons" },
  { law: "encode_conforms", section: "what is written is accepted", with: ["every listed name is accepted"],
    from: "      RBool{True{}}", to: "      RBool{False{}}",
    why: "enc writes false where the schema accepts only true (dec reads either, so the round trip holds)", failsIn: "ec" },
];

runMutants(import.meta.dir, MUTANTS);
