// bend-schema's mutants: for each law, a change to core.bend that makes it
// false, an instance of that law the change turns false -- its counterexample,
// at tiny literals -- and the def the proof must then fail in. The harness is
// bend-falsify's runMutants, which also runs the counterexample: it must check
// on the core and fail on the mutant, so the law is shown false and not merely
// asserted. test.sh runs this.
//
// A counterexample is a Bend equation over the core imported as C and nothing
// else, so it can read only the core's own defs. Two kinds of mutant make a
// law's falsehood wider than one equation can hold. decode_encode's two
// strengthen wf, and dec and enc never read wf, so theirs states the
// hypothesis instead: wf(s) == False on the core and True on the mutant.
// check_accurate's later_f_path mutant moves the path check reports, and
// defect reads the path it is given, so that one builds the path with the
// core's own later_f_path -- what check reports, on each core. Both mutants
// still have to fail the proof, in `de` and `field_path_end`.

import { type Mutant, runMutants } from "bend-falsify";

const EXACT = "check finds nothing exactly when the value conforms";

const MUTANTS: Mutant[] = [
  { law: "tagged_meaning", section: "a tagged case reads the object without its tag",
    from: "      pick_bool(is_tag(k, n, x), conforms(~rule, cs, drop_key(k, x), None{}), conforms(~rule, rest, x, None{}))",
    to: "      pick_bool(is_tag(k, n, x), conforms(~rule, cs, x, None{}), conforms(~rule, rest, x, None{}))",
    counter: "{C.conforms(~C.no_rule, C.STagged{\"t\", \"a\", C.SStrict{C.SEnd{}}, C.STagEnd{\"t\"}}, C.RKey{\"t\", C.RStr{\"a\"}, C.REnd{}}, None{}) == True{} : Bool}",
    why: "a case sees the tag, so a strict case refuses a good value", failsIn: "LAWS.tagged_meaning" },
  { law: "tag_end_refuses", section: "the end of a tagged chain accepts nothing",
    from: "      False{}  # the end of a tagged chain: no case matched", to: "      True{}",
    counter: "{C.conforms(~C.no_rule, C.STagEnd{\"t\"}, C.REnd{}, None{}) == False{} : Bool}",
    why: "the end of a chain accepts anything", failsIn: "LAWS.tag_end_refuses" },
  { law: "drop_first", section: "drop_key takes out the first key it names",
    from: "      pick_raw(String.eq(j, k), o, RKey{j, v, drop_key(k, o)})", to: "      pick_raw(String.eq(j, k), RKey{j, v, o}, RKey{j, v, drop_key(k, o)})",
    counter: "{C.drop_key(\"k\", C.RKey{\"k\", C.RNum{1n}, C.REnd{}}) == C.REnd{} : C.Raw}",
    why: "drop_key keeps the tag, so the case sees it", failsIn: "drop_self" },
  { law: "drop_other", section: "drop_key leaves every other key as it was",
    from: "      pick_raw(String.eq(j, k), o, RKey{j, v, drop_key(k, o)})", to: "      pick_raw(String.eq(j, k), o, drop_key(k, o))",
    counter: "{C.lookup(\"j\", C.drop_key(\"k\", C.RKey{\"j\", C.RNum{1n}, C.REnd{}})) == C.lookup(\"j\", C.RKey{\"j\", C.RNum{1n}, C.REnd{}}) : C.Raw}",
    why: "drop_key drops every key up to the tag (drop_self, which the section uses through the decoder tools, sees it first)", failsIn: "drop_self" },
  { law: "strict_meaning", section: "a strict object has no other key",
    from: "      Bool.and(in_names(k, ns), no_extra(ns, o))", to: "      in_names(k, ns)",
    counter: "{C.conforms(~C.no_rule, C.SStrict{C.SField{\"a\", C.SNat{}, C.SEnd{}}}, C.RKey{\"a\", C.RNum{1n}, C.RKey{\"x\", C.RNum{2n}, C.REnd{}}}, None{}) == False{} : Bool}",
    why: "no_extra looks at the first key only, so a later unknown key conforms", failsIn: "strict_count" },
  { law: "check_exact", section: EXACT,
    from: "      pick_err(in_names(k, ns), extra_err(ns, o), Some{Err{AtKey{k} <> Nil{}, UnknownKey{}}})", to: "      pick_err(in_names(k, ns), None{}, Some{Err{AtKey{k} <> Nil{}, UnknownKey{}}})",
    counter: "{Maybe.is_none(&2, C.Err, C.check(~C.no_rule, C.SStrict{C.SField{\"a\", C.SNat{}, C.SEnd{}}}, C.RKey{\"a\", C.RNum{1n}, C.RKey{\"x\", C.RNum{2n}, C.REnd{}}}, None{})) == False{} : Bool}",
    why: "check stops after the first known key, so a later unknown key passes check though it does not conform", failsIn: "extra_exact" },
  { law: "check_accurate", section: "what check reports is there", with: [EXACT],
    from: "      guard(Bool.and(has_key(k, r), Bool.not(in_names(k, ns))), Some{UnknownKey{}})", to: "      guard(Bool.not(in_names(k, ns)), Some{NotObject{}})",
    counter: "{C.defect(~C.no_rule, C.SStrict{C.SField{\"a\", C.SNat{}, C.SEnd{}}}, C.RKey{\"a\", C.RNum{1n}, C.RKey{\"x\", C.RNum{2n}, C.REnd{}}}, None{}, C.AtKey{\"x\"} <> Nil{}) == Some{C.UnknownKey{}} : Maybe<&2, C.Why>}",
    why: "defect replays an unknown key as the wrong reason", failsIn: "extra_lift" },
  { law: "str_len_in_meaning", section: "a string's length is in its bounds",
    from: "  Bool.and(Nat.is_le(lo, String.length(x)), Nat.is_le(String.length(x), hi))",
    to: "  Bool.and(Nat.is_le(lo, String.length(x)), Nat.is_lt(String.length(x), hi))",
    counter: "{Maybe.is_none(&2, C.Err, C.str_len_in(0n, 1n, C.RStr{\"a\"})) == True{} : Bool}",
    why: "a string exactly hi long is refused (str_len_ok is the test str_len_in reports, and what an SStrLen means)", failsIn: "LAWS.str_len_in_meaning" },
  { law: "nat_in_meaning", section: "a number is in its bounds",
    from: "  Bool.and(Nat.is_le(lo, n), Nat.is_le(n, hi))",
    to: "  Nat.is_le(lo, n)",
    counter: "{Maybe.is_none(&2, C.Err, C.nat_in(0n, 1n, C.RNum{2n})) == False{} : Bool}",
    why: "a number past hi is let through (num_ok is the test nat_in reports, and what an SNatIn means)", failsIn: "LAWS.nat_in_meaning" },
  { law: "sbool_meaning", section: "a boolean, and nothing else",
    from: "      True{}  # any boolean is a boolean, and nothing else is",
    to: "      False{}  # any boolean is a boolean, and nothing else is",
    counter: "{C.conforms(~C.no_rule, C.SBool{}, C.RBool{True{}}, None{}) == C.is_bool(C.RBool{True{}}) : Bool}",
    why: "a boolean is refused, so SBool accepts nothing", failsIn: "sbool_go" },
  { law: "snat_in_meaning", section: "a number's bounds, as a constructor",
    from: "      num_ok(lo, hi, n)",
    to: "      Nat.is_le(lo, n)",
    counter: "{C.conforms(~C.no_rule, C.SNatIn{0n, 1n}, C.RNum{2n}, None{}) == False{} : Bool}", nth: 1,
    why: "SNatIn drops its upper bound, so a number past hi conforms (the first of the two lines that read num_ok: conforms', not bounds_ok's)", failsIn: "LAWS.snat_in_meaning" },
  { law: "sstr_len_meaning", section: "a string's length, as a constructor",
    from: "      Bool.and(conforms(~rule, s2, x, prev), len_ok(lo, hi, x))",
    to: "      Bool.and(conforms(~rule, s2, x, prev), True{})",
    counter: "{C.conforms(~C.no_rule, C.SStrLen{1n, 3n, C.SStr{}}, C.RStr{\"\"}, None{}) == False{} : Bool}",
    why: "SStrLen drops its bounds, so a string of any length conforms", failsIn: "LAWS.sstr_len_meaning" },
  { law: "slist_len_meaning", section: "a list's element count, as a constructor",
    from: "      Bool.and(list_len_ok(lo, hi, r), conforms(~rule, s2, r, None{}))",
    to: "      conforms(~rule, s2, r, None{})",
    counter: "{C.conforms(~C.no_rule, C.SListLen{1n, 3n, C.SList{C.SNat{}}}, C.RNil{}, None{}) == False{} : Bool}",
    why: "SListLen drops its bounds, so a list of any element count conforms", failsIn: "LAWS.slist_len_meaning" },
  { law: "soptional_meaning", section: "an optional field, as a constructor",
    from: "      Bool.or(is_missing(x), conforms(~rule, inner, x, None{}))",
    to: "      Bool.or(is_missing(x), True{})",
    counter: "{C.conforms(~C.no_rule, C.SOptional{C.SNat{}}, C.RStr{\"a\"}, None{}) == False{} : Bool}",
    why: "SOptional accepts every value that is not absent, whatever the inner says", failsIn: "LAWS.soptional_meaning" },
  { law: "check_exact", section: EXACT,
    from: "      here(missing_or(x, NotNat{}))", to: "      None{}",
    counter: "{Maybe.is_none(&2, C.Err, C.check(~C.no_rule, C.SNat{}, C.RStr{\"a\"}, None{})) == False{} : Bool}", nth: 1,
    why: "a value that is not a number passes check, though it does not conform (the first of the two lines: the SNat arm, not the SNatIn one)", failsIn: "exact" },
  { law: "check_accurate", section: "what check reports is there", with: [EXACT],
    from: "      AtField{1n+k, n} <> q", to: "      AtField{k, n} <> q",
    counter: "{C.defect(~C.no_rule, C.SField{\"a\", C.SNat{}, C.SField{\"b\", C.SNat{}, C.SEnd{}}}, C.RKey{\"a\", C.RNum{1n}, C.RKey{\"b\", C.RStr{\"x\"}, C.REnd{}}}, None{}, C.later_f_path(C.AtField{0n, \"b\"} <> Nil{})) == Some{C.NotNat{}} : Maybe<&2, C.Why>}",
    why: "an error in a later field names the field before it", failsIn: "field_path_end" },
  { law: "check_exact", section: EXACT,
    from: "      first(check(~rule, s2, x, prev), rule(tag, x))", to: "      check(~rule, s2, x, prev)",
    counter: "{Maybe.is_none(&2, C.Err, C.check(~(t => r => C.nat_in(1n, 2n, r)), C.SRule{C.SNat{}, 0n}, C.RNum{0n}, None{})) == False{} : Bool}",
    why: "check forgets the rule, so a value the rule refuses passes", failsIn: "exact" },
  { law: "check_accurate", section: "what check reports is there", with: [EXACT],
    from: "      pick_why(conforms(~rule, s2, x, prev), rule_defect(rule(tag, x), q), defect(~rule, s2, x, prev, q))", to: "      defect(~rule, s2, x, prev, q)",
    counter: "{C.defect(~(t => r => C.nat_in(1n, 2n, r)), C.SRule{C.SNat{}, 0n}, C.RNum{0n}, None{}, Nil{}) == Some{C.NotIn{1n, 2n}} : Maybe<&2, C.Why>}",
    why: "defect never replays the rule, so a rule's error is not found there", failsIn: "acc" },
  { law: "too_large_reported", section: "a too big value is reported where it stands",
    from: "      TooLarge{}", to: "      NotNat{}",
    counter: "{C.check(~C.no_rule, C.SNat{}, C.RTooBig{}, None{}) == Some{C.Err{Nil{}, C.TooLarge{}}} : Maybe<&2, C.Err>}",
    why: "a node the codec refused to build is reported as the schema kind's own reason, so a value too big to walk reads as a value of the wrong shape", failsIn: "too_large_go" },
  { law: "enum_accepts", section: "every listed name is accepted",
    from: "      Bool.or(String.eq(x, n), in_names(x, t))", to: "      Bool.and(String.eq(x, n), in_names(x, t))",
    counter: "{C.conforms(~C.no_rule, C.SEnum{\"a\" <> (\"b\" <> Nil{})}, C.RStr{\"b\"}, None{}) == True{} : Bool}",
    why: "a name is found only if it is every name, so listed names are refused", failsIn: "names_has" },
  { law: "enum_admits", section: "an accepted string is one of the names",
    from: "      Bool.or(String.eq(x, n), in_names(x, t))", to: "      Bool.or(True{}, in_names(x, t))",
    counter: "{C.conforms(~C.no_rule, C.SEnum{\"a\" <> Nil{}}, C.RStr{\"b\"}, None{}) == False{} : Bool}",
    why: "any string is accepted by a non-empty list", failsIn: "one_of" },
  { law: "variant_meaning", section: "a variant chain, read by counting",
    from: "      pick_bool(is_missing(lookup(name, RKey{k, v, o})), conforms(~rule, rest, RKey{k, v, o}, None{}), Bool.and(conforms(~rule, vs, lookup(name, RKey{k, v, o}), None{}), none_present(rest, RKey{k, v, o})))",
    to: "      pick_bool(is_missing(lookup(name, RKey{k, v, o})), conforms(~rule, rest, RKey{k, v, o}, None{}), conforms(~rule, vs, lookup(name, RKey{k, v, o}), None{}))",
    counter: "{C.conforms(~C.no_rule, C.SVariant{\"a\", C.SNat{}, C.SVariant{\"b\", C.SNat{}, C.SVEnd{}}}, C.RKey{\"a\", C.RNum{1n}, C.RKey{\"b\", C.RNum{2n}, C.REnd{}}}, None{}) == False{} : Bool}",
    why: "conforms stops at the first key it finds, so two keys conform", failsIn: "vm_raw" },
  { law: "check_exact", section: EXACT,
    from: "      here(TooLong{})", to: "      None{}",
    counter: "{Maybe.is_none(&2, C.Err, C.check(~C.no_rule, C.STuple{C.SNat{}, C.STEnd{}}, C.RCons{C.RNum{1n}, C.RCons{C.RNum{2n}, C.RNil{}}}, None{})) == False{} : Bool}",
    why: "check lets a tuple with an extra element through, though it does not conform", failsIn: "exact" },
  { law: "check_accurate", section: "what check reports is there", with: [EXACT],
    from: "      at_end(TooShort{}, q)", to: "      at_end(TooLong{}, q)",
    counter: "{C.defect(~C.no_rule, C.STuple{C.SNat{}, C.STEnd{}}, C.RNil{}, None{}, Nil{}) == Some{C.TooShort{}} : Maybe<&2, C.Why>}",
    why: "defect replays a missing position as an extra one", failsIn: "acc" },
  { law: "tuple_meaning", section: "a tuple means its positions", with: ["a variant chain, read by counting"],
    from: "      Bool.and(conforms(~rule, ts, h, None{}), conforms(~rule, rest, t, None{}))", to: "      conforms(~rule, rest, t, None{})",
    counter: "{C.conforms(~C.no_rule, C.STuple{C.SNat{}, C.STEnd{}}, C.RCons{C.RStr{\"a\"}, C.RNil{}}, None{}) == False{} : Bool}",
    why: "conforms skips a tuple's position (check would have to agree, and then exact and accurate still hold)", failsIn: "tm" },
  { law: "decode_encode", section: "what was written reads back as itself",
    from: "      Bool.and(wf(fs), Bool.and(fresh_f(n, rest), wf(rest)))", to: "      Bool.and(wf(fs), wf(rest))",
    counter: "{C.wf(C.SField{\"a\", C.SNat{}, C.SField{\"a\", C.SNat{}, C.SEnd{}}}) == False{} : Bool}",
    why: "wf lets a record name a key twice, and the second field reads the first one's value", failsIn: "de" },
  { law: "decode_encode", section: "what was written reads back as itself",
    from: "      Bool.and(Bool.not(nullable(i)), wf(i))", to: "      wf(i)",
    counter: "{C.wf(C.SOpt{C.SOpt{C.SNat{}}}) == False{} : Bool}",
    why: "wf lets an optional value be optional, and Some{None} is written null, read back as None", failsIn: "de" },
  { law: "checked_decodes", section: "a value check accepts can be read",
    from: "      Some{x <> xs}", to: "      None{}",
    counter: "{Maybe.is_some(&2, C.Meaning(C.SList{C.SNat{}}), C.dec(C.SList{C.SNat{}}, C.RCons{C.RNum{1n}, C.RNil{}})) == True{} : Bool}",
    why: "dec refuses every non-empty list, though a list of conforming elements conforms", failsIn: "some_cons" },
  { law: "encode_conforms", section: "what is written is accepted", with: ["every listed name is accepted"],
    from: "      RBool{True{}}", to: "      RBool{False{}}",
    counter: "{C.conforms(~C.no_rule, C.STrue{}, C.enc(C.STrue{}, Unit{}), None{}) == True{} : Bool}",
    why: "enc writes false where the schema accepts only true (dec reads either, so the round trip holds)", failsIn: "ec" },
];

runMutants(import.meta.dir, MUTANTS);
