// gen.ts — the same schema, on the Bend side.
//
// A project writes its schema once, with `s` (src/index.ts), and this prints
// the same schema as Bend defs, so a Bend core checks the host's values against
// the one definition. Nothing is written twice, and nothing can drift: the
// generated file is output, not a second source.
//
// What is printed is `Schema.node` — the core's own Schema value, which `toNode`
// builds and `wf` accepts, so an ill-formed schema throws before anything is
// written. This file interprets nothing; it writes that value out in Bend's
// syntax. A constructor it has no case for throws here, and a case it prints
// wrongly is a Bend compile error. Neither can be a silent difference.
//
// The constructor names and their field order are core/core.bend's own
// (`type Schema is Data:`), which is why this file goes with bend-schema rather
// than in a package of its own: a new constructor touches both.

import type { BendList, Schema as Node } from "../dist-core/core.mjs";
import type { Schema } from "./index";

const q = (s: string) => JSON.stringify(s);
const n = (x: bigint | number) => `${x}n`;
const ctor = (name: string, args: string[]) =>
  args.length ? `S.${name}{${args.join(", ")}}` : `S.${name}{}`;

// A `List<&2, String>` as Bend source: "a" <> "b" <> Nil{}.
function strList(l: BendList<string>): string {
  const out: string[] = [];
  let cur: BendList<string> = l;
  while (cur.$ === "Con") {
    out.push(q(cur.head));
    cur = cur.tail;
  }
  return out.length ? out.join(" <> ") + " <> Nil{}" : "Nil{}";
}

/** One schema as a Bend expression, e.g. `S.SNatIn{1n, 64n}`. */
export function printNode(x: Node): string {
  switch (x.$) {
    case "SNat":
    case "SStr":
    case "SBool":
    case "STrue":
    case "SJson":
    case "SEnd":
    case "STEnd":
    case "SVEnd":
      return ctor(x.$, []);
    case "SNatIn":
      return ctor("SNatIn", [n(x.lo as bigint), n(x.hi as bigint)]);
    case "SStrLen":
      return ctor("SStrLen", [n(x.lo as bigint), n(x.hi as bigint), printNode(x.s as Node)]);
    case "SOpt":
      return ctor("SOpt", [printNode(x.inner as Node)]);
    case "SOptional":
      return ctor("SOptional", [printNode(x.inner as Node)]);
    case "SList":
      return ctor("SList", [printNode(x.elem as Node)]);
    case "SListLen":
      return ctor("SListLen", [n(x.lo as bigint), n(x.hi as bigint), printNode(x.s as Node)]);
    case "SStrict":
      return ctor("SStrict", [printNode(x.s as Node)]);
    case "SField":
      return ctor("SField", [q(x.name as string), printNode(x.s as Node), printNode(x.rest as Node)]);
    case "SEnum":
      return ctor("SEnum", [strList(x.names as BendList<string>)]);
    case "STuple":
      return ctor("STuple", [printNode(x.s as Node), printNode(x.rest as Node)]);
    case "SVariant":
      return ctor("SVariant", [q(x.name as string), printNode(x.s as Node), printNode(x.rest as Node)]);
    case "STagged":
      return ctor("STagged", [q(x.key as string), q(x.name as string), printNode(x.s as Node), printNode(x.rest as Node)]);
    case "STagEnd":
      return ctor("STagEnd", [q(x.key as string)]);
    default:
      throw new Error(`gen: no Bend form for ${x.$}`);
  }
}

/** A whole Bend file: one `def <key>_schema() -> S.Schema:` per key. */
export function emit(
  schemas: Record<string, Schema<unknown>>,
  opts: { libPath: string; from: string },
): string {
  const defs: string[] = [];
  for (const [name, s] of Object.entries(schemas)) {
    if (!/^[A-Za-z_]\w*$/.test(name)) throw new Error(`gen: "${name}" is not a Bend name`);
    if (!s || typeof s.node !== "object") throw new Error(`gen: ${name} is not a Schema`);
    defs.push(`def ${name}_schema() -> S.Schema:\n  ${printNode(s.node as Node)}\n`);
  }
  if (defs.length === 0) throw new Error("gen: nothing to print");
  return (
    `import Base\nimport ${opts.libPath} as S\n\n` +
    `# Generated by bend-schema from ${opts.from}. Do not edit; regenerate.\n\n` +
    defs.join("\n")
  );
}
